# Generated by Django 4.0.2 on 2022-04-03 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=4)),
                ('number', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('name', models.CharField(default='', max_length=100)),
                ('section', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('computing_id', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('attendees', models.ManyToManyField(related_name='studies', to='study.Student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.course')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='roster',
            field=models.ManyToManyField(blank=True, related_name='courses', to='study.Student'),
        ),
    ]
