# Generated by Django 4.0.2 on 2022-03-26 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('computing_id', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('study_subject', models.CharField(default='', max_length=4)),
                ('study_number', models.CharField(default='', max_length=4)),
                ('study_name', models.CharField(default='', max_length=100)),
                ('study_section', models.CharField(default='', max_length=3)),
                ('attendees', models.ManyToManyField(related_name='student_attendees', to='study.Student')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=4)),
                ('course_number', models.CharField(default='', max_length=4)),
                ('course_name', models.CharField(default='', max_length=100)),
                ('course_section', models.CharField(default='', max_length=3)),
                ('student_course', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
