# Generated by Django 4.0.2 on 2022-04-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
    ]
