# Generated by Django 4.0.2 on 2022-04-03 20:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0002_alter_course_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.CharField(default='', max_length=2600),
        ),
        migrations.AddField(
            model_name='student',
            name='pref_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='student',
            name='student_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='computing_id',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
