# Generated by Django 3.2.12 on 2022-03-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_study_student_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='student_study',
        ),
    ]
